/**
 * Central configuration for the Eisenhower workspace.
 * Every top-level constant lives here: other files only declare functions,
 * so Apps Script's file load order can never hit an uninitialized constant.
 */

const CONFIG = {
  sheets: { todo: 'TODO', archive: 'Archive' },
  legacySheets: ['Eisenhower Matrix', 'Dashboard'], // generated by older versions, removed on rebuild
  todoRows: 30,             // minimum rows on the TODO / Archive sheets (incl. header)
  spareRows: 10,            // empty rows kept below the last task on rebuild
  headerHeight: 38,         // Modern SaaS executive header height
  rowHeight: 26,            // Comfortable SaaS row breathing room
  gapWidth: 18,             // Spacer column between the task table and the quadrants
  quadrantWidth: 175,       // Quadrant column width
  archivedWidth: 140,
  panelPollMs: 1000,        // how often the task sidebar checks the selected row
  autoOpenPanel: true,      // open the task sidebar whenever the spreadsheet loads (web only)
  includeSampleTasks: true, // seed sample tasks when the TODO sheet is first created
  defaultStatus: 'To Do',   // filled in automatically when a new task is typed
  dateFormat: 'mmm d, yyyy',
  font: 'Inter',            // Modern SaaS geometric typeface
};

const THEME = {
  header: '#0f172a',          // Task table header: Modern SaaS Slate 900
  headerText: '#ffffff',      // Task table header text
  border: '#cbd5e1',          // Clean slate grid borders (replaces harsh black)
  borderLight: '#f1f5f9',     // Subtle cell divider
  faint: '#94a3b8',           // Muted text for Done / completed tasks
  doneBg: '#f8fafc',          // Soft background tint for Done tasks

  // Sheet Tab Colors
  todoTab: '#4f46e5',         // Vibrant Indigo tab
  archiveTab: '#64748b',      // Cool Slate tab
  archiveHeader: '#1e293b',   // Archive table header (Deep Slate)
  archiveHeaderText: '#ffffff',

  // Priority checkbox active highlights
  importantBg: '#fef3c7',     // Soft Warm Amber
  importantFg: '#92400e',     // Amber text/border
  urgentBg: '#fee2e2',        // Soft Warm Rose
  urgentFg: '#991b1b',        // Rose text/border

  // Spacer column separator
  spacerBg: '#f8fafc',
};

// Task table columns, in order. Formulas look columns up by key,
// so reordering here is safe as long as Important and Urgent stay adjacent.
const COLUMNS = [
  { key: 'task',      header: 'Tasks',     width: 360 },
  { key: 'status',    header: 'Status',    width: 110 },
  { key: 'important', header: 'Important', width: 80 },
  { key: 'urgent',    header: 'Urgent',    width: 80 },
];

const COL = {}; // key -> 1-based column index
COLUMNS.forEach((c, i) => { COL[c.key] = i + 1; });

const STATUSES = {
  'To Do':       { bg: '#e0e7ff', fg: '#3730a3' }, // Indigo soft badge
  'In Progress': { bg: '#dbeafe', fg: '#1e40af' }, // Royal Blue badge
  'Done':        { bg: '#dcfce7', fg: '#166534' }, // Emerald Green badge
  'Blocked':     { bg: '#fee2e2', fg: '#991b1b' }, // Crimson Rose badge
};

// One live column per quadrant on the TODO sheet, in this order.
// Distinct vibrant header colors and gentle pastel column tints.
const QUADRANTS = [
  {
    id: 'Q1',
    title: 'Do Now',
    headerLabel: 'Q1 · Do Now',
    important: true,
    urgent: true,
    headerBg: '#dc2626',      // Crimson Red header
    headerFg: '#ffffff',
    bg: '#fef2f2',            // Soft rose column tint
    text: '#991b1b',          // Dark rose text
    accent: '#ef4444',
  },
  {
    id: 'Q2',
    title: 'Schedule',
    headerLabel: 'Q2 · Schedule',
    important: true,
    urgent: false,
    headerBg: '#16a34a',      // Emerald Green header
    headerFg: '#ffffff',
    bg: '#f0fdf4',            // Soft emerald column tint
    text: '#166534',          // Dark emerald text
    accent: '#22c55e',
  },
  {
    id: 'Q3',
    title: 'Delegate',
    headerLabel: 'Q3 · Delegate',
    important: false,
    urgent: true,
    headerBg: '#d97706',      // Amber Orange header
    headerFg: '#ffffff',
    bg: '#fffbeb',            // Soft amber column tint
    text: '#92400e',          // Dark amber text
    accent: '#f59e0b',
  },
  {
    id: 'Q4',
    title: 'Delete',
    headerLabel: 'Q4 · Delete',
    important: false,
    urgent: false,
    headerBg: '#6366f1',      // Vibrant Indigo header
    headerFg: '#ffffff',
    bg: '#f5f3ff',            // Soft lavender column tint
    text: '#4338ca',          // Dark indigo text
    accent: '#818cf8',
  },
];

// First quadrant column (one spacer column after the task table) and the sheet's last column
const MATRIX_COL = COLUMNS.length + 2;
const TODO_LAST_COL = MATRIX_COL + QUADRANTS.length - 1;

const SAMPLE_TASKS = [
  { task: 'Fix checkout bug reported by customers', status: 'In Progress', important: true,  urgent: true },
  { task: 'Prepare investor update deck',           status: 'To Do',       important: true,  urgent: true },
  { task: 'Plan Q4 product roadmap',                status: 'In Progress', important: true,  urgent: false },
  { task: 'Weekly 1:1s with direct reports',        status: 'To Do',       important: true,  urgent: false },
  { task: 'Reply to vendor pricing emails',         status: 'To Do',       important: false, urgent: true },
  { task: 'Book team offsite logistics',            status: 'Blocked',     important: false, urgent: true },
  { task: 'Reorganize old Drive folders',           status: 'To Do',       important: false, urgent: false },
  { task: 'Review newsletter subscriptions',        status: 'Done',        important: false, urgent: false },
];
