/**
 * Central configuration for the Eisenhower workspace.
 * Every top-level constant lives here: other files only declare functions,
 * so Apps Script's file load order can never hit an uninitialized constant.
 */

const CONFIG = {
  sheets: { todo: 'TODO', archive: 'Archive' },
  legacySheets: ['Eisenhower Matrix', 'Dashboard'], // generated by older versions, removed on rebuild
  todoRows: 30,             // minimum rows on the TODO / Archive sheets (incl. header)
  spareRows: 10,            // empty rows kept below the last task on rebuild
  headerHeight: 32,
  rowHeight: 21,
  gapWidth: 16,             // spacer column between the task table and the quadrants
  quadrantWidth: 160,
  archivedWidth: 140,
  panelPollMs: 1000,        // how often the task sidebar checks the selected row
  autoOpenPanel: true,      // open the task sidebar whenever the spreadsheet loads (web only)
  includeSampleTasks: true, // seed sample tasks when the TODO sheet is first created
  defaultStatus: 'To Do',   // filled in automatically when a new task is typed
  dateFormat: 'mmm d, yyyy',
  font: 'Arial',
};

const THEME = {
  header: '#000000',
  headerText: '#ffffff',
  border: '#000000',
  faint: '#9ca3af',
  archiveTab: '#9ca3af',
};

// Task table columns, in order. Formulas look columns up by key,
// so reordering here is safe as long as Important and Urgent stay adjacent.
const COLUMNS = [
  { key: 'task',      header: 'Tasks',     width: 340 },
  { key: 'status',    header: 'Status',    width: 100 },
  { key: 'important', header: 'Important', width: 70 },
  { key: 'urgent',    header: 'Urgent',    width: 70 },
];

const COL = {}; // key -> 1-based column index
COLUMNS.forEach((c, i) => { COL[c.key] = i + 1; });

const STATUSES = {
  'To Do':       { bg: '#f3f4f6', fg: '#374151' },
  'In Progress': { bg: '#dbeafe', fg: '#1e40af' },
  'Done':        { bg: '#dcfce7', fg: '#166534' },
  'Blocked':     { bg: '#fee2e2', fg: '#991b1b' },
};

// One live column per quadrant on the TODO sheet, in this order. Colors are used by the sidebar.
const QUADRANTS = [
  { id: 'Q1', title: 'Do Now',   important: true,  urgent: true,  bg: '#fef2f2', text: '#991b1b', accent: '#ef4444' },
  { id: 'Q2', title: 'Schedule', important: true,  urgent: false, bg: '#f0fdf4', text: '#166534', accent: '#22c55e' },
  { id: 'Q3', title: 'Delegate', important: false, urgent: true,  bg: '#fffbeb', text: '#92400e', accent: '#f59e0b' },
  { id: 'Q4', title: 'Delete',   important: false, urgent: false, bg: '#f9fafb', text: '#374151', accent: '#9ca3af' },
];

// First quadrant column (one spacer column after the task table) and the sheet's last column
const MATRIX_COL = COLUMNS.length + 2;
const TODO_LAST_COL = MATRIX_COL + QUADRANTS.length - 1;

const SAMPLE_TASKS = [
  { task: 'Fix checkout bug reported by customers', status: 'In Progress', important: true,  urgent: true },
  { task: 'Prepare investor update deck',           status: 'To Do',       important: true,  urgent: true },
  { task: 'Plan Q4 product roadmap',                status: 'In Progress', important: true,  urgent: false },
  { task: 'Weekly 1:1s with direct reports',        status: 'To Do',       important: true,  urgent: false },
  { task: 'Reply to vendor pricing emails',         status: 'To Do',       important: false, urgent: true },
  { task: 'Book team offsite logistics',            status: 'Blocked',     important: false, urgent: true },
  { task: 'Reorganize old Drive folders',           status: 'To Do',       important: false, urgent: false },
  { task: 'Review newsletter subscriptions',        status: 'Done',        important: false, urgent: false },
];
